'''
this file selects the most effective electrode/electrodes

% /**************************************************************************** 
%  * Job:             electrode selection                    * 
%  *                                                                          * 
%  *Inputs: patien_number, is_kalman (True if we want to apply kalman filter
    and False otherwise
    Outputs: prepared_data {'y':y_windowed, 'features': features}
                y_windowed (DataFrame) is classes lables for each window
                features (Dictionary) is features data for each electrode 
%  *                                                                          * 
%  * Generated on:    Sun, May 21, 2017                                       * 
%  * Generated by:    Hassan Eldeeb                                                    * 
%  * Version:         1                                                       * 
%  ****************************************************************************/ 
'''

from preprocessing import preprocessing
from feature_extraction import feature_extraction
from kalman_filter import kalman_filter
from PrepareYVector import getY
from PrepareWindowsVector import getWindows
import pandas as pd